### ISSUE TITLE
Graphql builtins suffer from encoding issues (breaks server/clients)

### ISSUE THREAD

**Issue by Overbryd** [shopgun/graphql-erlang#136]
Hi everyone,

I am running against the latest master version.

And I am seeing strange encoding problems when querying the default responses with GraphiQL.
For demonstration purposes I used your `graphql-erlang-tutorial` application.

So this is the response header that cowboy sends for the introspection query.
It states that content will be utf-8 encoded:

```
HTTP/1.1 200 OK
server: Cowboy
date: Tue, 19 Dec 2017 18:44:19 GMT
content-encoding: gzip
content-length: 4069
content-type: application/json; charset=utf-8
vary: accept
```

**snip**

But inside the response, documentation annotations can be found that have encoding issues.
Here is one example of the introspection of the SCALAR type `Float`:

```
{"description":"Floating point values, IEEE 754, but not �infty, nor NaN","enumValues":null,"fields":null,"inputFields":null,"interfaces":null,"kind":"SCALAR","name":"Float","possibleTypes":null}
```

When looking up the source for this string, I found this in `src/graphql_builtins.erl:15`:

```
    	description => "Floating point values, IEEE 754, but not ±infty, nor NaN" }},
```

So there is definitely something fishy going on. Unfortunately I do not know how to fix this quickly.
I think maybe there is an encoding issue when fetching `graphql-erlang` as a dependency (it definitely happens on a vanilla **graphql-erlang-tutorial** application).

This issue prevents some clients, and also my server, to render introspection queries/results.

**Comment by jlouis** [comment]
What might be going on is something on the way out in the encoding indeed. Does your PR fix it? (I'll merge it because it is correct anyhow)

**Comment by Overbryd** [comment]
Yep, tested the PR with


```
make compile
make test
```

on both develop and master.

The issue can be closed, as this fixed the introspection queries for me.

**Comment by jlouis** [comment]
Perfect. Travis also runs "make dialyzer" in addition, but since it passed those tests, everything is fine :)
