### ISSUE TITLE
Proposal: Rename atom null -> nil

### ISSUE THREAD

**Issue by Overbryd** [shopgun/graphql-erlang#138]
Hi,

this might seem a little counter-intuitive at first, but hear me out:

Using graphql-erlang from Elixir is currently slightly pesky, since one has to either traverse the whole tree/list of results to replace `null` with `nil` or nastily patch JSON encoding to treat `null` as `null` instead of the default Atom -> binary `"null"`.

I have been going back and forth with some hacky solutions, but thought maybe its worth having this discussion upstream here.

I am happy to help by sending in a PR that is currently representing a project-wide rename of the `null`-Atom to `nil`. It would give the folks over in Elixir land instant compatibility to bind to this excellent library.

Here is something [to have a laugh about while pondering](https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare). (It's all ALGOL W's fault.)

**Comment by gausby** [comment]
It is a great idea, but we would like to be able to specify the value for the null value. In some systems it might be good to have `undefined` as the null value, others might need `null` (the JSON encoders in Erlang converts that into JSON `null`) and Elixir wants `nil` (the JSON encoders in Elixir converts that into JSON `null`)…

We already have a plan for this, but unfortunately we haven't moved on it yet. You can read the discussion here: #92

**Comment by gausby** [comment]
@Overbryd Does this answer your question, and can I close this issue (on the grounds of it being a duplicate) ?

**Comment by Overbryd** [comment]
duplicate. Thanks
