### ISSUE TITLE
Handle empty string operationName properly(?)

### ISSUE THREAD

**Issue by klarstrup** [shopgun/graphql-erlang#159]
Currently if a request is sent where operationName is an empty string (`""`) it won't match an unnamed operation:
![image](https://user-images.githubusercontent.com/1567633/38733176-3b505f48-3f21-11e8-99a0-51176ca3d8bc.png)
![image](https://user-images.githubusercontent.com/1567633/38733179-3d8e2d3a-3f21-11e8-8c7c-ec0a7143c1b9.png)

It probably(?) should.

**Comment by jlouis** [comment]
Should be fixed, and will be merged into the systems ASAP
