### ISSUE TITLE
Errornous handling of nulls in inlined field arguments

### ISSUE THREAD

**Issue by ptrf** [shopgun/graphql-erlang#189]
Given `field(input: FieldInput!): ...` and `input FieldInput { attribute: Int }`, the following two queries should work the same, if `$fieldInput` is an input variable containing `{ "attr": X }`

1. `query A($fieldinput: FieldInput!) [...] { field(input: $fieldinput) {... } }`
2. `query B [...] { field(input: {attr: X}) {... } }`

But if we set `X` to `null` the former works, while the latter ends up passing `{enum, <<"null">>}` to the underlying field resolver resource.

**Comment by ptrf** [comment]
Proposal to get fix under way; create PR with test case that allows failure reproduction.

**Comment by jlouis** [comment]
Fixed in 2ae1af7619e61b8d14905fbeb0b4f56165e9b449 I believe.
