### ISSUE TITLE
Support user defined enum variant values?

### ISSUE THREAD

**Issue by ptrf** [shopgun/graphql-erlang#46]
Commit 6bdc1b6b2b051249c001daccbf139123e0dc0b55 introduces the `variants/1` function in the `graphql_schema_parse`, which assings a numeric value to each enum variant, starting with 0 and incrementing by 1 for each consecutive variant. This reduces boilerplate code dramatically, but unfortunately, this setup:

1. Makes the ordering of variants in the `.graphql` schema file important 
2. Requires the maintenance of a separate enum value "translation" for components that does not interact with objects through the graph.

Currently, this affects moose, as moose needs to be able to distinguish and search among different authentication method representation, that are parametrized by the `AuthenticationMethodType` enum. Prior to the new way of doing things(TM), variant values were explicitly defined and could be 
canonicalized as this example shows

```erlang
{enum, { ..., 
    values => #{ 
                'AUTHENTICATION_METHOD_FACEBOOK' =>
                    #{ value => gryphon_person:authentication_method_type(facebook),
                       description => "Authentication method facilitated by Facebook."
                    },
                  ...
        }
    }
}
```

@jlouis Can we come up with a solution allowing variant representation values to be determined or looked up outside of the graphql?

**Comment by jlouis** [comment]
This is now complete. We have a way to do Enum mapping correctly though transformation functions. Closing.
