### ISSUE TITLE
Missing query and mutation type result in unrelated error message

### ISSUE THREAD

**Issue by gausby** [shopgun/graphql-erlang#48]
A schema with missing mutation and query types will result in the error `schema_not_found`, even though the schema file does exist. We should consider a better error for this scenario.

**Comment by jlouis** [comment]
To solve this, we should probably fail on a missing root schema with an error message that is more clear to the user. And if we can't find either the Query or Mutation target in the root-schema we should also use a more direct error message.

**Comment by jlouis** [comment]
I've merged the PR which fixes this. The new rules are:

If you give a schema-block with things defined, it will be checked that those types exist. If you don't give a schema block, it will try to pick up defaults and fail if that doesn't work. In short, the code should complain with an error that says "The type Query doesn't exist in the schema" or something such.
