### ISSUE TITLE
heavy lager dependencies

### ISSUE THREAD

**Issue by goertzenator** [shopgun/graphql-erlang#52]
I am exploring using graphql on an embedded device, and the dependence on lager pulls in approximately 2MB of .beam (lager->goldrush->compiler), whereas graphql itself is only 0.38MB.

I see lager is used in only 4 places.  Is depending on lager crucial here?  I've never used lager before so I don't know what it is bringing to the table.

**Comment by jlouis** [comment]
I don't think we need the `lager` dependency. We tend to use lager a lot internally at shopgun, so it is often you just drop a few lines here and there when you are building stuff. If it is only used in a few places, we should definitely replace it with the error logger and get rid of `lager`.

**Comment by jlouis** [comment]
Tracked in #53 with a patch which should fix this. I'll merge once I'm somewhat confident it works as expected.

**Comment by jlouis** [comment]
Master should have a `lager`-free version of GraphQL now. We haven't used it much on our end, so we are interested in errors. @ptrf took a look as well and improved my bad error canaries and cleaned up stuff as well.

**Comment by jlouis** [comment]
Close this if it works for you!

**Comment by jlouis** [comment]
Closing this.
