### ISSUE TITLE
Annotating values in an enum results in a error

### ISSUE THREAD

**Issue by gausby** [shopgun/graphql-erlang#62]
Annotating a field of an enum in a schema will result in a crash when evaluating the graphql schema:

How to reproduce:

Add something like this to the schema:
```graphql
enum Status {
  +description(text: "This will make the parser crash")
  SUCCESS
  FAILURE
}
```
Reload the graphql schema in an interface like *graphiql*.

**Comment by jlouis** [comment]
Indeed, this is a lacking feature. We have changes underway on the enum system and once they are going in, we should get this piggybacked on top of those changes I think.

**Comment by jlouis** [comment]
This can now proceed since the enum changes went in.

**Comment by jlouis** [comment]
Some initial analysis of this one:

- [ ] Introduce a new record `#p_enum_value{}` for enum values in the system. This allows us to attach an annotation to an enum value.
- [ ] Parse this new value form correctly in the system.
- [ ] When generating enum values, hoist the enum value description into the schema.
- [ ] Write a test case which makes sure we can extract the enum information out of the schema again.

**Comment by jlouis** [comment]
There is now a PR for this case as well in the brewer.
