### ISSUE TITLE
Empty parenthesis in query definitions result in server crash

### ISSUE THREAD

**Issue by gausby** [shopgun/graphql-erlang#77]
Defining a query node like this will crash the GraphQL server:
```graphql
type Query {
  # …
  nodes(): [Node]!
}
```
This works:
```graphql
type Query {
  # …
  nodes: [Node]!
}
```
Is this valid or should it error with a reason?

**Comment by jlouis** [comment]
I think the notion should be valid (after some thought). The next phase is to create PR in which we alter the dungeon to contain a schema-field like the above such that we have a failing test case. Once we have a reproducer, we can look into what parts of the code base should change for this (it is probably the schema-parser which has the bug).

**Comment by jlouis** [comment]
Looking at the specification Oct2016 section 2.6 arguments have the form
```
'(' ArgumentList ')'
```

in the grammar. In section A.3, the notion of a "List" is defined to be `1..n` elements, not `0..n` elements.

Hence, the grammar section of the specification disallows this, so it is not a bug.
