### ISSUE TITLE
Argument resolver crashes when omitting a nullable input field of type list

### ISSUE THREAD

**Issue by ptrf** [shopgun/graphql-erlang#78]
The schema snippets below sets the stage

```graphql
input I {
     nonNull: String!
     list: [String]
}

type Mutation {
     m(input: I!): ...
}
```

GraphQL crashes with runtime error `{case_clause, null}` in [`graphql_execute.erl`](https://github.com/shopgun/graphql-erlang/blob/47ae34df85e036b27791e79eea613acde165cd19/src/graphql_execute.erl#L533) when attempting to perform this mutation:

```graphql
mutation M {
  m(input: {nonNull: "non-nullable string"}) {
    ...
  }
}
```

**Comment by ptrf** [comment]
If the `list` field of input type `I` has a default value, the crash doesn't happen - i.e. `list: [String] = []`.

**Comment by ptrf** [comment]
The bug only triggers for arguments written in the query doc. The following mutation:

```graphql
mutation M($input: I!) {
  m(input: $input) {
    ...
  }
}
```

with variables `{ "input": {"nonNull": "non-nullable string"} }` works fine.

**Comment by jlouis** [comment]
Fix merged, lets close this one.
